//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRServiceCalls.ApplicationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationOutcome", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class OperationOutcome : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.ApplicationService.OutcomeDetails OutcomeDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.ApplicationService.OutcomeDetails OutcomeDetails {
            get {
                return this.OutcomeDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeDetailsField, value) != true)) {
                    this.OutcomeDetailsField = value;
                    this.RaisePropertyChanged("OutcomeDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutcomeDetails", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.ApplicationService.InvalidCredentials))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.ApplicationService.PinNumberLockout))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.ApplicationService.TaskAlreadyComplete))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.ApplicationService.LoginLockout))]
    public partial class OutcomeDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.ApplicationService.OperationOutcomeStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.ApplicationService.OperationOutcomeStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidCredentials", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class InvalidCredentials : HRServiceCalls.ApplicationService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PinNumberLockout", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PinNumberLockout : HRServiceCalls.ApplicationService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskAlreadyComplete", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class TaskAlreadyComplete : HRServiceCalls.ApplicationService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginLockout", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LoginLockout : HRServiceCalls.ApplicationService.OutcomeDetails {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationOutcomeStatus", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    public enum OperationOutcomeStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemException = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApplicationService.IApplicationService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IApplicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/GetMobileHelpText", ReplyAction="http://tempuri.org/IApplicationService/GetMobileHelpTextResponse")]
        string GetMobileHelpText(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/GetMobileHelpText", ReplyAction="http://tempuri.org/IApplicationService/GetMobileHelpTextResponse")]
        System.Threading.Tasks.Task<string> GetMobileHelpTextAsync(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/LogError", ReplyAction="http://tempuri.org/IApplicationService/LogErrorResponse")]
        HRServiceCalls.ApplicationService.OperationOutcome LogError(System.Guid cascadeSessionToken, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicationService/LogError", ReplyAction="http://tempuri.org/IApplicationService/LogErrorResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.ApplicationService.OperationOutcome> LogErrorAsync(System.Guid cascadeSessionToken, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplicationServiceChannel : HRServiceCalls.ApplicationService.IApplicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationServiceClient : System.ServiceModel.ClientBase<HRServiceCalls.ApplicationService.IApplicationService>, HRServiceCalls.ApplicationService.IApplicationService {
        
        public ApplicationServiceClient() {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMobileHelpText(System.Guid cascadeSessionToken) {
            return base.Channel.GetMobileHelpText(cascadeSessionToken);
        }
        
        public System.Threading.Tasks.Task<string> GetMobileHelpTextAsync(System.Guid cascadeSessionToken) {
            return base.Channel.GetMobileHelpTextAsync(cascadeSessionToken);
        }
        
        public HRServiceCalls.ApplicationService.OperationOutcome LogError(System.Guid cascadeSessionToken, string message) {
            return base.Channel.LogError(cascadeSessionToken, message);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.ApplicationService.OperationOutcome> LogErrorAsync(System.Guid cascadeSessionToken, string message) {
            return base.Channel.LogErrorAsync(cascadeSessionToken, message);
        }
    }
}
