//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRServiceCalls.EmployeeGroupService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeadCount", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class HeadCount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDetails", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class EmployeeDetails : HRServiceCalls.EmployeeGroupService.OperationOutcome {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeDescription {
            get {
                return this.EmployeeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeDescriptionField, value) != true)) {
                    this.EmployeeDescriptionField = value;
                    this.RaisePropertyChanged("EmployeeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken {
            get {
                return this.SessionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokenField, value) != true)) {
                    this.SessionTokenField = value;
                    this.RaisePropertyChanged("SessionToken");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationOutcome", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.EmployeeGroupService.EmployeeDetails))]
    public partial class OperationOutcome : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.EmployeeGroupService.OutcomeDetails OutcomeDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.EmployeeGroupService.OutcomeDetails OutcomeDetails {
            get {
                return this.OutcomeDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeDetailsField, value) != true)) {
                    this.OutcomeDetailsField = value;
                    this.RaisePropertyChanged("OutcomeDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutcomeDetails", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.EmployeeGroupService.InvalidCredentials))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.EmployeeGroupService.PinNumberLockout))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.EmployeeGroupService.TaskAlreadyComplete))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.EmployeeGroupService.LoginLockout))]
    public partial class OutcomeDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.EmployeeGroupService.OperationOutcomeStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.EmployeeGroupService.OperationOutcomeStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidCredentials", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class InvalidCredentials : HRServiceCalls.EmployeeGroupService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PinNumberLockout", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PinNumberLockout : HRServiceCalls.EmployeeGroupService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskAlreadyComplete", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class TaskAlreadyComplete : HRServiceCalls.EmployeeGroupService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginLockout", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LoginLockout : HRServiceCalls.EmployeeGroupService.OutcomeDetails {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationOutcomeStatus", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    public enum OperationOutcomeStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemException = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeGroupService.IEmployeeGroupService")]
    public interface IEmployeeGroupService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeGroupService/GetGroupName", ReplyAction="http://tempuri.org/IEmployeeGroupService/GetGroupNameResponse")]
        string GetGroupName(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeGroupService/GetGroupName", ReplyAction="http://tempuri.org/IEmployeeGroupService/GetGroupNameResponse")]
        System.Threading.Tasks.Task<string> GetGroupNameAsync(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeGroupService/GetHeadCountByStatus", ReplyAction="http://tempuri.org/IEmployeeGroupService/GetHeadCountByStatusResponse")]
        HRServiceCalls.EmployeeGroupService.HeadCount[] GetHeadCountByStatus(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeGroupService/GetHeadCountByStatus", ReplyAction="http://tempuri.org/IEmployeeGroupService/GetHeadCountByStatusResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.EmployeeGroupService.HeadCount[]> GetHeadCountByStatusAsync(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeGroupService/GetEmployeesForAttendanceStatus", ReplyAction="http://tempuri.org/IEmployeeGroupService/GetEmployeesForAttendanceStatusResponse")]
        HRServiceCalls.EmployeeGroupService.EmployeeDetails[] GetEmployeesForAttendanceStatus(System.Guid cascadeSessionToken, string attendanceStatus, int rowStartNo, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeGroupService/GetEmployeesForAttendanceStatus", ReplyAction="http://tempuri.org/IEmployeeGroupService/GetEmployeesForAttendanceStatusResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.EmployeeGroupService.EmployeeDetails[]> GetEmployeesForAttendanceStatusAsync(System.Guid cascadeSessionToken, string attendanceStatus, int rowStartNo, int pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeGroupServiceChannel : HRServiceCalls.EmployeeGroupService.IEmployeeGroupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeGroupServiceClient : System.ServiceModel.ClientBase<HRServiceCalls.EmployeeGroupService.IEmployeeGroupService>, HRServiceCalls.EmployeeGroupService.IEmployeeGroupService {
        
        public EmployeeGroupServiceClient() {
        }
        
        public EmployeeGroupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeGroupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeGroupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeGroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetGroupName(System.Guid cascadeSessionToken) {
            return base.Channel.GetGroupName(cascadeSessionToken);
        }
        
        public System.Threading.Tasks.Task<string> GetGroupNameAsync(System.Guid cascadeSessionToken) {
            return base.Channel.GetGroupNameAsync(cascadeSessionToken);
        }
        
        public HRServiceCalls.EmployeeGroupService.HeadCount[] GetHeadCountByStatus(System.Guid cascadeSessionToken) {
            return base.Channel.GetHeadCountByStatus(cascadeSessionToken);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.EmployeeGroupService.HeadCount[]> GetHeadCountByStatusAsync(System.Guid cascadeSessionToken) {
            return base.Channel.GetHeadCountByStatusAsync(cascadeSessionToken);
        }
        
        public HRServiceCalls.EmployeeGroupService.EmployeeDetails[] GetEmployeesForAttendanceStatus(System.Guid cascadeSessionToken, string attendanceStatus, int rowStartNo, int pageSize) {
            return base.Channel.GetEmployeesForAttendanceStatus(cascadeSessionToken, attendanceStatus, rowStartNo, pageSize);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.EmployeeGroupService.EmployeeDetails[]> GetEmployeesForAttendanceStatusAsync(System.Guid cascadeSessionToken, string attendanceStatus, int rowStartNo, int pageSize) {
            return base.Channel.GetEmployeesForAttendanceStatusAsync(cascadeSessionToken, attendanceStatus, rowStartNo, pageSize);
        }
    }
}
