//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRServiceCalls.EmployeeDetailsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationOutcome", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.EmployeeDetailsService.EmployeeDetails))]
    public partial class OperationOutcome : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.EmployeeDetailsService.OutcomeDetails OutcomeDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.EmployeeDetailsService.OutcomeDetails OutcomeDetails {
            get {
                return this.OutcomeDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeDetailsField, value) != true)) {
                    this.OutcomeDetailsField = value;
                    this.RaisePropertyChanged("OutcomeDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutcomeDetails", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.EmployeeDetailsService.InvalidCredentials))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.EmployeeDetailsService.PinNumberLockout))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.EmployeeDetailsService.TaskAlreadyComplete))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.EmployeeDetailsService.LoginLockout))]
    public partial class OutcomeDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.EmployeeDetailsService.OperationOutcomeStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.EmployeeDetailsService.OperationOutcomeStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDetails", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class EmployeeDetails : HRServiceCalls.EmployeeDetailsService.OperationOutcome {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeDescription {
            get {
                return this.EmployeeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeDescriptionField, value) != true)) {
                    this.EmployeeDescriptionField = value;
                    this.RaisePropertyChanged("EmployeeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken {
            get {
                return this.SessionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokenField, value) != true)) {
                    this.SessionTokenField = value;
                    this.RaisePropertyChanged("SessionToken");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidCredentials", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class InvalidCredentials : HRServiceCalls.EmployeeDetailsService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PinNumberLockout", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PinNumberLockout : HRServiceCalls.EmployeeDetailsService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskAlreadyComplete", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class TaskAlreadyComplete : HRServiceCalls.EmployeeDetailsService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginLockout", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LoginLockout : HRServiceCalls.EmployeeDetailsService.OutcomeDetails {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationOutcomeStatus", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    public enum OperationOutcomeStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemException = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeDetailsService.IEmployeeDetailsService")]
    public interface IEmployeeDetailsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeDetailsService/GetEmployeeDetails", ReplyAction="http://tempuri.org/IEmployeeDetailsService/GetEmployeeDetailsResponse")]
        HRServiceCalls.EmployeeDetailsService.EmployeeDetails GetEmployeeDetails(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeDetailsService/GetEmployeeDetails", ReplyAction="http://tempuri.org/IEmployeeDetailsService/GetEmployeeDetailsResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.EmployeeDetailsService.EmployeeDetails> GetEmployeeDetailsAsync(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeDetailsService/GetHeadlineStatistics", ReplyAction="http://tempuri.org/IEmployeeDetailsService/GetHeadlineStatisticsResponse")]
        System.Collections.Generic.Dictionary<string, int> GetHeadlineStatistics(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeDetailsService/GetHeadlineStatistics", ReplyAction="http://tempuri.org/IEmployeeDetailsService/GetHeadlineStatisticsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetHeadlineStatisticsAsync(System.Guid cascadeSessionToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeDetailsServiceChannel : HRServiceCalls.EmployeeDetailsService.IEmployeeDetailsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeDetailsServiceClient : System.ServiceModel.ClientBase<HRServiceCalls.EmployeeDetailsService.IEmployeeDetailsService>, HRServiceCalls.EmployeeDetailsService.IEmployeeDetailsService {
        
        public EmployeeDetailsServiceClient() {
        }
        
        public EmployeeDetailsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeDetailsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeDetailsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeDetailsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HRServiceCalls.EmployeeDetailsService.EmployeeDetails GetEmployeeDetails(System.Guid cascadeSessionToken) {
            return base.Channel.GetEmployeeDetails(cascadeSessionToken);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.EmployeeDetailsService.EmployeeDetails> GetEmployeeDetailsAsync(System.Guid cascadeSessionToken) {
            return base.Channel.GetEmployeeDetailsAsync(cascadeSessionToken);
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetHeadlineStatistics(System.Guid cascadeSessionToken) {
            return base.Channel.GetHeadlineStatistics(cascadeSessionToken);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetHeadlineStatisticsAsync(System.Guid cascadeSessionToken) {
            return base.Channel.GetHeadlineStatisticsAsync(cascadeSessionToken);
        }
    }
}
