namespace HRServiceCalls
{
    public class RoleItemKey
    {

        public const string MOBILE_MYDETAILS_PAGE = "MOBILE_MYDETAILS_PAGE";
        public const string MOBILE_HEADCOUNTSTATUS_PAGE = "MOBILE_HEADCOUNTSTATUS_PAGE";
        public const string MOBILE_MYHOLIDAYS_PAGE = "MOBILE_MYHOLIDAYS_PAGE";
        public const string MOBILE_MYPAYSLIP_PAGE = "MOBILE_MYPAYSLIP_PAGE";
        public const string MOBILE_MYTASKS_PAGE = "MOBILE_MYTASKS_PAGE";
        public const string MOBILE_HOLIDAYAUTHORISATIONS_PAGE = "MOBILE_HOLIDAYAUTHORISATIONS_PAGE";
        public const string MOBILE_BOOKHOLIDAY_PAGE = "MOBILE_BOOKHOLIDAY_PAGE";
        public const string MOBILE_CANCELHOLIDAY_PAGE = "MOBILE_CANCELHOLIDAY_PAGE";
        public const string MOBILE_EMPLOYEESFORATTENDANCESTATUS_PAGE = "MOBILE_EMPLOYEESFORATTENDANCESTATUS_PAGE";
        public const string MOBILE_HOLIDAYREQUESTDETAILS_PAGE = "MOBILE_HOLIDAYREQUESTDETAILS_PAGE";
        public const string MOBILE_HOME_PAGE = "MOBILE_HOME_PAGE";
        public const string MOBILE_TASKDETAILS_PAGE = "MOBILE_TASKDETAILS_PAGE";
    }
}
