//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRServiceCalls.HolidayService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationOutcome", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.Request))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.HolidayBalance))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.SingleHoliday))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.PagePermission))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.HolidayList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.GenericBool))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.MultiOperationOutcome))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.ObjectsPagerOfHolidayN_SsdewcJ))]
    public partial class OperationOutcome : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.HolidayService.OutcomeDetails OutcomeDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.HolidayService.OutcomeDetails OutcomeDetails {
            get {
                return this.OutcomeDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeDetailsField, value) != true)) {
                    this.OutcomeDetailsField = value;
                    this.RaisePropertyChanged("OutcomeDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutcomeDetails", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.InvalidCredentials))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.PinNumberLockout))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.TaskAlreadyComplete))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.LoginLockout))]
    public partial class OutcomeDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.HolidayService.OperationOutcomeStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.HolidayService.OperationOutcomeStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.ObjectsPagerOfHolidayN_SsdewcJ))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.OperationOutcome))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.OutcomeDetails))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.OperationOutcomeStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.InvalidCredentials))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.PinNumberLockout))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.TaskAlreadyComplete))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.LoginLockout))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.Holiday[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.Holiday))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.AttendanceDayPart))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.AttendanceUnit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.HolidayBalance))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.OverBookAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.SingleHoliday))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.PagePermission))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.PageAccessLevelType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.HolidayList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.GenericBool))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.RequestType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.HolidayService.MultiOperationOutcome))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Guid[]))]
    public partial class Request : HRServiceCalls.HolidayService.OperationOutcome {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object RequestDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object RequestDetails {
            get {
                return this.RequestDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestDetailsField, value) != true)) {
                    this.RequestDetailsField = value;
                    this.RaisePropertyChanged("RequestDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestID {
            get {
                return this.RequestIDField;
            }
            set {
                if ((this.RequestIDField.Equals(value) != true)) {
                    this.RequestIDField = value;
                    this.RaisePropertyChanged("RequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestType {
            get {
                return this.RequestTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTypeField, value) != true)) {
                    this.RequestTypeField = value;
                    this.RaisePropertyChanged("RequestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateType {
            get {
                return this.UpdateTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateTypeField, value) != true)) {
                    this.UpdateTypeField = value;
                    this.RaisePropertyChanged("UpdateType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolidayBalance", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class HolidayBalance : HRServiceCalls.HolidayService.OperationOutcome {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EntitlementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EntitlementYearEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EntitlementYearStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.HolidayService.OverBookAction OverBookActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TakenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.HolidayService.AttendanceUnit UnitsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Entitlement {
            get {
                return this.EntitlementField;
            }
            set {
                if ((this.EntitlementField.Equals(value) != true)) {
                    this.EntitlementField = value;
                    this.RaisePropertyChanged("Entitlement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EntitlementYearEnd {
            get {
                return this.EntitlementYearEndField;
            }
            set {
                if ((this.EntitlementYearEndField.Equals(value) != true)) {
                    this.EntitlementYearEndField = value;
                    this.RaisePropertyChanged("EntitlementYearEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EntitlementYearStart {
            get {
                return this.EntitlementYearStartField;
            }
            set {
                if ((this.EntitlementYearStartField.Equals(value) != true)) {
                    this.EntitlementYearStartField = value;
                    this.RaisePropertyChanged("EntitlementYearStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.HolidayService.OverBookAction OverBookAction {
            get {
                return this.OverBookActionField;
            }
            set {
                if ((this.OverBookActionField.Equals(value) != true)) {
                    this.OverBookActionField = value;
                    this.RaisePropertyChanged("OverBookAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Taken {
            get {
                return this.TakenField;
            }
            set {
                if ((this.TakenField.Equals(value) != true)) {
                    this.TakenField = value;
                    this.RaisePropertyChanged("Taken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.HolidayService.AttendanceUnit Units {
            get {
                return this.UnitsField;
            }
            set {
                if ((this.UnitsField.Equals(value) != true)) {
                    this.UnitsField = value;
                    this.RaisePropertyChanged("Units");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleHoliday", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class SingleHoliday : HRServiceCalls.HolidayService.OperationOutcome {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.HolidayService.Holiday HolidayDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.HolidayService.Holiday HolidayDetails {
            get {
                return this.HolidayDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.HolidayDetailsField, value) != true)) {
                    this.HolidayDetailsField = value;
                    this.RaisePropertyChanged("HolidayDetails");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagePermission", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PagePermission : HRServiceCalls.HolidayService.OperationOutcome {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.HolidayService.PageAccessLevelType AccessLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanDeleteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.HolidayService.PageAccessLevelType AccessLevel {
            get {
                return this.AccessLevelField;
            }
            set {
                if ((this.AccessLevelField.Equals(value) != true)) {
                    this.AccessLevelField = value;
                    this.RaisePropertyChanged("AccessLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanDelete {
            get {
                return this.CanDeleteField;
            }
            set {
                if ((this.CanDeleteField.Equals(value) != true)) {
                    this.CanDeleteField = value;
                    this.RaisePropertyChanged("CanDelete");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolidayList", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class HolidayList : HRServiceCalls.HolidayService.OperationOutcome {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.HolidayService.Holiday[] HolidaysField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.HolidayService.Holiday[] Holidays {
            get {
                return this.HolidaysField;
            }
            set {
                if ((object.ReferenceEquals(this.HolidaysField, value) != true)) {
                    this.HolidaysField = value;
                    this.RaisePropertyChanged("Holidays");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericBool", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GenericBool : HRServiceCalls.HolidayService.OperationOutcome {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultiOperationOutcome", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class MultiOperationOutcome : HRServiceCalls.HolidayService.OperationOutcome {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperationExceptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperationsFailedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperationsSucceededField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperationExceptions {
            get {
                return this.OperationExceptionsField;
            }
            set {
                if ((this.OperationExceptionsField.Equals(value) != true)) {
                    this.OperationExceptionsField = value;
                    this.RaisePropertyChanged("OperationExceptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperationsFailed {
            get {
                return this.OperationsFailedField;
            }
            set {
                if ((this.OperationsFailedField.Equals(value) != true)) {
                    this.OperationsFailedField = value;
                    this.RaisePropertyChanged("OperationsFailed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperationsSucceeded {
            get {
                return this.OperationsSucceededField;
            }
            set {
                if ((this.OperationsSucceededField.Equals(value) != true)) {
                    this.OperationsSucceededField = value;
                    this.RaisePropertyChanged("OperationsSucceeded");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectsPagerOfHolidayN_SsdewcJ", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ObjectsPagerOfHolidayN_SsdewcJ : HRServiceCalls.HolidayService.OperationOutcome {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFirstPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLastPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.HolidayService.Holiday[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumberOfItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFirstPage {
            get {
                return this.IsFirstPageField;
            }
            set {
                if ((this.IsFirstPageField.Equals(value) != true)) {
                    this.IsFirstPageField = value;
                    this.RaisePropertyChanged("IsFirstPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLastPage {
            get {
                return this.IsLastPageField;
            }
            set {
                if ((this.IsLastPageField.Equals(value) != true)) {
                    this.IsLastPageField = value;
                    this.RaisePropertyChanged("IsLastPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.HolidayService.Holiday[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPages {
            get {
                return this.NumberOfPagesField;
            }
            set {
                if ((this.NumberOfPagesField.Equals(value) != true)) {
                    this.NumberOfPagesField = value;
                    this.RaisePropertyChanged("NumberOfPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNumberOfItems {
            get {
                return this.TotalNumberOfItemsField;
            }
            set {
                if ((this.TotalNumberOfItemsField.Equals(value) != true)) {
                    this.TotalNumberOfItemsField = value;
                    this.RaisePropertyChanged("TotalNumberOfItems");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Holiday", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Holiday : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceAfterRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.HolidayService.Request ChildRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.HolidayService.AttendanceDayPart DurationDayPartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.HolidayService.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.HolidayService.AttendanceUnit UnitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BalanceAfterRequest {
            get {
                return this.BalanceAfterRequestField;
            }
            set {
                if ((this.BalanceAfterRequestField.Equals(value) != true)) {
                    this.BalanceAfterRequestField = value;
                    this.RaisePropertyChanged("BalanceAfterRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.HolidayService.Request ChildRequest {
            get {
                return this.ChildRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildRequestField, value) != true)) {
                    this.ChildRequestField = value;
                    this.RaisePropertyChanged("ChildRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.HolidayService.AttendanceDayPart DurationDayPart {
            get {
                return this.DurationDayPartField;
            }
            set {
                if ((this.DurationDayPartField.Equals(value) != true)) {
                    this.DurationDayPartField = value;
                    this.RaisePropertyChanged("DurationDayPart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeDescription {
            get {
                return this.EmployeeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeDescriptionField, value) != true)) {
                    this.EmployeeDescriptionField = value;
                    this.RaisePropertyChanged("EmployeeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.HolidayService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Ruid {
            get {
                return this.RuidField;
            }
            set {
                if ((this.RuidField.Equals(value) != true)) {
                    this.RuidField = value;
                    this.RaisePropertyChanged("Ruid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.HolidayService.AttendanceUnit Units {
            get {
                return this.UnitsField;
            }
            set {
                if ((this.UnitsField.Equals(value) != true)) {
                    this.UnitsField = value;
                    this.RaisePropertyChanged("Units");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidCredentials", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class InvalidCredentials : HRServiceCalls.HolidayService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PinNumberLockout", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PinNumberLockout : HRServiceCalls.HolidayService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskAlreadyComplete", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class TaskAlreadyComplete : HRServiceCalls.HolidayService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginLockout", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LoginLockout : HRServiceCalls.HolidayService.OutcomeDetails {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationOutcomeStatus", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    public enum OperationOutcomeStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemException = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttendanceDayPart", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    public enum AttendanceDayPart : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AM = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullDay = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mixed = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttendanceUnit", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    public enum AttendanceUnit : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Days = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Minutes = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OverBookAction", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    public enum OverBookAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Prevent = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageAccessLevelType", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    public enum PageAccessLevelType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReadOnly = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Request = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Direct = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestType", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    public enum RequestType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Holiday = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HolidayService.IHolidayService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IHolidayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetEmployeeCurrentEntitlementYearHolidays_Debu" +
            "g", ReplyAction="http://tempuri.org/IHolidayService/GetEmployeeCurrentEntitlementYearHolidays_Debu" +
            "gResponse")]
        void GetEmployeeCurrentEntitlementYearHolidays_Debug(System.Guid cascadeSessionToken, int pageSize, int pageNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetEmployeeCurrentEntitlementYearHolidays_Debu" +
            "g", ReplyAction="http://tempuri.org/IHolidayService/GetEmployeeCurrentEntitlementYearHolidays_Debu" +
            "gResponse")]
        System.Threading.Tasks.Task GetEmployeeCurrentEntitlementYearHolidays_DebugAsync(System.Guid cascadeSessionToken, int pageSize, int pageNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetEmployeeCurrentEntitlementYearHolidays", ReplyAction="http://tempuri.org/IHolidayService/GetEmployeeCurrentEntitlementYearHolidaysRespo" +
            "nse")]
        HRServiceCalls.HolidayService.ObjectsPagerOfHolidayN_SsdewcJ GetEmployeeCurrentEntitlementYearHolidays(System.Guid cascadeSessionToken, int pageSize, int pageNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetEmployeeCurrentEntitlementYearHolidays", ReplyAction="http://tempuri.org/IHolidayService/GetEmployeeCurrentEntitlementYearHolidaysRespo" +
            "nse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.ObjectsPagerOfHolidayN_SsdewcJ> GetEmployeeCurrentEntitlementYearHolidaysAsync(System.Guid cascadeSessionToken, int pageSize, int pageNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetEmployeeBalance", ReplyAction="http://tempuri.org/IHolidayService/GetEmployeeBalanceResponse")]
        HRServiceCalls.HolidayService.HolidayBalance GetEmployeeBalance(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetEmployeeBalance", ReplyAction="http://tempuri.org/IHolidayService/GetEmployeeBalanceResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.HolidayBalance> GetEmployeeBalanceAsync(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetEmployeeBalanceForRequest", ReplyAction="http://tempuri.org/IHolidayService/GetEmployeeBalanceForRequestResponse")]
        HRServiceCalls.HolidayService.HolidayBalance GetEmployeeBalanceForRequest(System.Guid cascadeSessionToken, System.Guid requestID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetEmployeeBalanceForRequest", ReplyAction="http://tempuri.org/IHolidayService/GetEmployeeBalanceForRequestResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.HolidayBalance> GetEmployeeBalanceForRequestAsync(System.Guid cascadeSessionToken, System.Guid requestID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetHolidayDuration", ReplyAction="http://tempuri.org/IHolidayService/GetHolidayDurationResponse")]
        HRServiceCalls.HolidayService.SingleHoliday GetHolidayDuration(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetHolidayDuration", ReplyAction="http://tempuri.org/IHolidayService/GetHolidayDurationResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.SingleHoliday> GetHolidayDurationAsync(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetPagePermission", ReplyAction="http://tempuri.org/IHolidayService/GetPagePermissionResponse")]
        HRServiceCalls.HolidayService.PagePermission GetPagePermission(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetPagePermission", ReplyAction="http://tempuri.org/IHolidayService/GetPagePermissionResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.PagePermission> GetPagePermissionAsync(System.Guid cascadeSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetHolidayClashes", ReplyAction="http://tempuri.org/IHolidayService/GetHolidayClashesResponse")]
        HRServiceCalls.HolidayService.HolidayList GetHolidayClashes(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetHolidayClashes", ReplyAction="http://tempuri.org/IHolidayService/GetHolidayClashesResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.HolidayList> GetHolidayClashesAsync(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/IsKeyPersonBlocking", ReplyAction="http://tempuri.org/IHolidayService/IsKeyPersonBlockingResponse")]
        HRServiceCalls.HolidayService.GenericBool IsKeyPersonBlocking(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/IsKeyPersonBlocking", ReplyAction="http://tempuri.org/IHolidayService/IsKeyPersonBlockingResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.GenericBool> IsKeyPersonBlockingAsync(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/CreateHoliday", ReplyAction="http://tempuri.org/IHolidayService/CreateHolidayResponse")]
        HRServiceCalls.HolidayService.OperationOutcome CreateHoliday(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/CreateHoliday", ReplyAction="http://tempuri.org/IHolidayService/CreateHolidayResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.OperationOutcome> CreateHolidayAsync(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/UpdateHoliday", ReplyAction="http://tempuri.org/IHolidayService/UpdateHolidayResponse")]
        HRServiceCalls.HolidayService.OperationOutcome UpdateHoliday(System.Guid cascadeSessionToken, System.Guid attendanceRuid, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/UpdateHoliday", ReplyAction="http://tempuri.org/IHolidayService/UpdateHolidayResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.OperationOutcome> UpdateHolidayAsync(System.Guid cascadeSessionToken, System.Guid attendanceRuid, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/DeleteHoliday", ReplyAction="http://tempuri.org/IHolidayService/DeleteHolidayResponse")]
        HRServiceCalls.HolidayService.OperationOutcome DeleteHoliday(System.Guid cascadeSessionToken, System.Guid attendanceRuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/DeleteHoliday", ReplyAction="http://tempuri.org/IHolidayService/DeleteHolidayResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.OperationOutcome> DeleteHolidayAsync(System.Guid cascadeSessionToken, System.Guid attendanceRuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetEmployeeHoliday", ReplyAction="http://tempuri.org/IHolidayService/GetEmployeeHolidayResponse")]
        HRServiceCalls.HolidayService.SingleHoliday GetEmployeeHoliday(System.Guid cascadeSessionToken, System.Guid attendanceRuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetEmployeeHoliday", ReplyAction="http://tempuri.org/IHolidayService/GetEmployeeHolidayResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.SingleHoliday> GetEmployeeHolidayAsync(System.Guid cascadeSessionToken, System.Guid attendanceRuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetTeamHolidayClashes", ReplyAction="http://tempuri.org/IHolidayService/GetTeamHolidayClashesResponse")]
        HRServiceCalls.HolidayService.HolidayList GetTeamHolidayClashes(System.Guid cascadeSessionToken, System.Guid requestid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetTeamHolidayClashes", ReplyAction="http://tempuri.org/IHolidayService/GetTeamHolidayClashesResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.HolidayList> GetTeamHolidayClashesAsync(System.Guid cascadeSessionToken, System.Guid requestid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetRequestsToAuthorise", ReplyAction="http://tempuri.org/IHolidayService/GetRequestsToAuthoriseResponse")]
        HRServiceCalls.HolidayService.ObjectsPagerOfHolidayN_SsdewcJ GetRequestsToAuthorise(System.Guid cascadeSessionToken, HRServiceCalls.HolidayService.RequestType requestType, int pageSize, int pageNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetRequestsToAuthorise", ReplyAction="http://tempuri.org/IHolidayService/GetRequestsToAuthoriseResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.ObjectsPagerOfHolidayN_SsdewcJ> GetRequestsToAuthoriseAsync(System.Guid cascadeSessionToken, HRServiceCalls.HolidayService.RequestType requestType, int pageSize, int pageNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetRequestsToAuthorise_debug", ReplyAction="http://tempuri.org/IHolidayService/GetRequestsToAuthorise_debugResponse")]
        void GetRequestsToAuthorise_debug(System.Guid cascadeSessionToken, HRServiceCalls.HolidayService.RequestType requestType, int pageSize, int pageNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetRequestsToAuthorise_debug", ReplyAction="http://tempuri.org/IHolidayService/GetRequestsToAuthorise_debugResponse")]
        System.Threading.Tasks.Task GetRequestsToAuthorise_debugAsync(System.Guid cascadeSessionToken, HRServiceCalls.HolidayService.RequestType requestType, int pageSize, int pageNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetRequestDetails", ReplyAction="http://tempuri.org/IHolidayService/GetRequestDetailsResponse")]
        HRServiceCalls.HolidayService.Request GetRequestDetails(System.Guid cascadeSessionToken, System.Guid requestid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetRequestDetails", ReplyAction="http://tempuri.org/IHolidayService/GetRequestDetailsResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.Request> GetRequestDetailsAsync(System.Guid cascadeSessionToken, System.Guid requestid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetRequestDetails_Debug", ReplyAction="http://tempuri.org/IHolidayService/GetRequestDetails_DebugResponse")]
        void GetRequestDetails_Debug(System.Guid cascadeSessionToken, System.Guid requestid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/GetRequestDetails_Debug", ReplyAction="http://tempuri.org/IHolidayService/GetRequestDetails_DebugResponse")]
        System.Threading.Tasks.Task GetRequestDetails_DebugAsync(System.Guid cascadeSessionToken, System.Guid requestid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/RejectRequests", ReplyAction="http://tempuri.org/IHolidayService/RejectRequestsResponse")]
        HRServiceCalls.HolidayService.MultiOperationOutcome RejectRequests(System.Guid cascadeSessionToken, System.Guid[] requestids, string comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/RejectRequests", ReplyAction="http://tempuri.org/IHolidayService/RejectRequestsResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.MultiOperationOutcome> RejectRequestsAsync(System.Guid cascadeSessionToken, System.Guid[] requestids, string comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/ApproveRequests", ReplyAction="http://tempuri.org/IHolidayService/ApproveRequestsResponse")]
        HRServiceCalls.HolidayService.MultiOperationOutcome ApproveRequests(System.Guid cascadeSessionToken, System.Guid[] requestids, string comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHolidayService/ApproveRequests", ReplyAction="http://tempuri.org/IHolidayService/ApproveRequestsResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.HolidayService.MultiOperationOutcome> ApproveRequestsAsync(System.Guid cascadeSessionToken, System.Guid[] requestids, string comments);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHolidayServiceChannel : HRServiceCalls.HolidayService.IHolidayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HolidayServiceClient : System.ServiceModel.ClientBase<HRServiceCalls.HolidayService.IHolidayService>, HRServiceCalls.HolidayService.IHolidayService {
        
        public HolidayServiceClient() {
        }
        
        public HolidayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HolidayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetEmployeeCurrentEntitlementYearHolidays_Debug(System.Guid cascadeSessionToken, int pageSize, int pageNumber) {
            base.Channel.GetEmployeeCurrentEntitlementYearHolidays_Debug(cascadeSessionToken, pageSize, pageNumber);
        }
        
        public System.Threading.Tasks.Task GetEmployeeCurrentEntitlementYearHolidays_DebugAsync(System.Guid cascadeSessionToken, int pageSize, int pageNumber) {
            return base.Channel.GetEmployeeCurrentEntitlementYearHolidays_DebugAsync(cascadeSessionToken, pageSize, pageNumber);
        }
        
        public HRServiceCalls.HolidayService.ObjectsPagerOfHolidayN_SsdewcJ GetEmployeeCurrentEntitlementYearHolidays(System.Guid cascadeSessionToken, int pageSize, int pageNumber) {
            return base.Channel.GetEmployeeCurrentEntitlementYearHolidays(cascadeSessionToken, pageSize, pageNumber);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.ObjectsPagerOfHolidayN_SsdewcJ> GetEmployeeCurrentEntitlementYearHolidaysAsync(System.Guid cascadeSessionToken, int pageSize, int pageNumber) {
            return base.Channel.GetEmployeeCurrentEntitlementYearHolidaysAsync(cascadeSessionToken, pageSize, pageNumber);
        }
        
        public HRServiceCalls.HolidayService.HolidayBalance GetEmployeeBalance(System.Guid cascadeSessionToken) {
            return base.Channel.GetEmployeeBalance(cascadeSessionToken);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.HolidayBalance> GetEmployeeBalanceAsync(System.Guid cascadeSessionToken) {
            return base.Channel.GetEmployeeBalanceAsync(cascadeSessionToken);
        }
        
        public HRServiceCalls.HolidayService.HolidayBalance GetEmployeeBalanceForRequest(System.Guid cascadeSessionToken, System.Guid requestID) {
            return base.Channel.GetEmployeeBalanceForRequest(cascadeSessionToken, requestID);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.HolidayBalance> GetEmployeeBalanceForRequestAsync(System.Guid cascadeSessionToken, System.Guid requestID) {
            return base.Channel.GetEmployeeBalanceForRequestAsync(cascadeSessionToken, requestID);
        }
        
        public HRServiceCalls.HolidayService.SingleHoliday GetHolidayDuration(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart) {
            return base.Channel.GetHolidayDuration(cascadeSessionToken, startDate, endDate, dayPart);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.SingleHoliday> GetHolidayDurationAsync(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart) {
            return base.Channel.GetHolidayDurationAsync(cascadeSessionToken, startDate, endDate, dayPart);
        }
        
        public HRServiceCalls.HolidayService.PagePermission GetPagePermission(System.Guid cascadeSessionToken) {
            return base.Channel.GetPagePermission(cascadeSessionToken);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.PagePermission> GetPagePermissionAsync(System.Guid cascadeSessionToken) {
            return base.Channel.GetPagePermissionAsync(cascadeSessionToken);
        }
        
        public HRServiceCalls.HolidayService.HolidayList GetHolidayClashes(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart) {
            return base.Channel.GetHolidayClashes(cascadeSessionToken, startDate, endDate, dayPart);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.HolidayList> GetHolidayClashesAsync(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart) {
            return base.Channel.GetHolidayClashesAsync(cascadeSessionToken, startDate, endDate, dayPart);
        }
        
        public HRServiceCalls.HolidayService.GenericBool IsKeyPersonBlocking(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart) {
            return base.Channel.IsKeyPersonBlocking(cascadeSessionToken, startDate, endDate, dayPart);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.GenericBool> IsKeyPersonBlockingAsync(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart) {
            return base.Channel.IsKeyPersonBlockingAsync(cascadeSessionToken, startDate, endDate, dayPart);
        }
        
        public HRServiceCalls.HolidayService.OperationOutcome CreateHoliday(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart) {
            return base.Channel.CreateHoliday(cascadeSessionToken, startDate, endDate, dayPart);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.OperationOutcome> CreateHolidayAsync(System.Guid cascadeSessionToken, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart) {
            return base.Channel.CreateHolidayAsync(cascadeSessionToken, startDate, endDate, dayPart);
        }
        
        public HRServiceCalls.HolidayService.OperationOutcome UpdateHoliday(System.Guid cascadeSessionToken, System.Guid attendanceRuid, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart) {
            return base.Channel.UpdateHoliday(cascadeSessionToken, attendanceRuid, startDate, endDate, dayPart);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.OperationOutcome> UpdateHolidayAsync(System.Guid cascadeSessionToken, System.Guid attendanceRuid, System.DateTime startDate, System.DateTime endDate, HRServiceCalls.HolidayService.AttendanceDayPart dayPart) {
            return base.Channel.UpdateHolidayAsync(cascadeSessionToken, attendanceRuid, startDate, endDate, dayPart);
        }
        
        public HRServiceCalls.HolidayService.OperationOutcome DeleteHoliday(System.Guid cascadeSessionToken, System.Guid attendanceRuid) {
            return base.Channel.DeleteHoliday(cascadeSessionToken, attendanceRuid);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.OperationOutcome> DeleteHolidayAsync(System.Guid cascadeSessionToken, System.Guid attendanceRuid) {
            return base.Channel.DeleteHolidayAsync(cascadeSessionToken, attendanceRuid);
        }
        
        public HRServiceCalls.HolidayService.SingleHoliday GetEmployeeHoliday(System.Guid cascadeSessionToken, System.Guid attendanceRuid) {
            return base.Channel.GetEmployeeHoliday(cascadeSessionToken, attendanceRuid);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.SingleHoliday> GetEmployeeHolidayAsync(System.Guid cascadeSessionToken, System.Guid attendanceRuid) {
            return base.Channel.GetEmployeeHolidayAsync(cascadeSessionToken, attendanceRuid);
        }
        
        public HRServiceCalls.HolidayService.HolidayList GetTeamHolidayClashes(System.Guid cascadeSessionToken, System.Guid requestid) {
            return base.Channel.GetTeamHolidayClashes(cascadeSessionToken, requestid);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.HolidayList> GetTeamHolidayClashesAsync(System.Guid cascadeSessionToken, System.Guid requestid) {
            return base.Channel.GetTeamHolidayClashesAsync(cascadeSessionToken, requestid);
        }
        
        public HRServiceCalls.HolidayService.ObjectsPagerOfHolidayN_SsdewcJ GetRequestsToAuthorise(System.Guid cascadeSessionToken, HRServiceCalls.HolidayService.RequestType requestType, int pageSize, int pageNumber) {
            return base.Channel.GetRequestsToAuthorise(cascadeSessionToken, requestType, pageSize, pageNumber);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.ObjectsPagerOfHolidayN_SsdewcJ> GetRequestsToAuthoriseAsync(System.Guid cascadeSessionToken, HRServiceCalls.HolidayService.RequestType requestType, int pageSize, int pageNumber) {
            return base.Channel.GetRequestsToAuthoriseAsync(cascadeSessionToken, requestType, pageSize, pageNumber);
        }
        
        public void GetRequestsToAuthorise_debug(System.Guid cascadeSessionToken, HRServiceCalls.HolidayService.RequestType requestType, int pageSize, int pageNumber) {
            base.Channel.GetRequestsToAuthorise_debug(cascadeSessionToken, requestType, pageSize, pageNumber);
        }
        
        public System.Threading.Tasks.Task GetRequestsToAuthorise_debugAsync(System.Guid cascadeSessionToken, HRServiceCalls.HolidayService.RequestType requestType, int pageSize, int pageNumber) {
            return base.Channel.GetRequestsToAuthorise_debugAsync(cascadeSessionToken, requestType, pageSize, pageNumber);
        }
        
        public HRServiceCalls.HolidayService.Request GetRequestDetails(System.Guid cascadeSessionToken, System.Guid requestid) {
            return base.Channel.GetRequestDetails(cascadeSessionToken, requestid);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.Request> GetRequestDetailsAsync(System.Guid cascadeSessionToken, System.Guid requestid) {
            return base.Channel.GetRequestDetailsAsync(cascadeSessionToken, requestid);
        }
        
        public void GetRequestDetails_Debug(System.Guid cascadeSessionToken, System.Guid requestid) {
            base.Channel.GetRequestDetails_Debug(cascadeSessionToken, requestid);
        }
        
        public System.Threading.Tasks.Task GetRequestDetails_DebugAsync(System.Guid cascadeSessionToken, System.Guid requestid) {
            return base.Channel.GetRequestDetails_DebugAsync(cascadeSessionToken, requestid);
        }
        
        public HRServiceCalls.HolidayService.MultiOperationOutcome RejectRequests(System.Guid cascadeSessionToken, System.Guid[] requestids, string comments) {
            return base.Channel.RejectRequests(cascadeSessionToken, requestids, comments);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.MultiOperationOutcome> RejectRequestsAsync(System.Guid cascadeSessionToken, System.Guid[] requestids, string comments) {
            return base.Channel.RejectRequestsAsync(cascadeSessionToken, requestids, comments);
        }
        
        public HRServiceCalls.HolidayService.MultiOperationOutcome ApproveRequests(System.Guid cascadeSessionToken, System.Guid[] requestids, string comments) {
            return base.Channel.ApproveRequests(cascadeSessionToken, requestids, comments);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.HolidayService.MultiOperationOutcome> ApproveRequestsAsync(System.Guid cascadeSessionToken, System.Guid[] requestids, string comments) {
            return base.Channel.ApproveRequestsAsync(cascadeSessionToken, requestids, comments);
        }
    }
}
