//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRServiceCalls.SecurityService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationOutcome", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.SecurityService.ObjectActions))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.SecurityService.RoleItems))]
    public partial class OperationOutcome : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.SecurityService.OutcomeDetails OutcomeDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.SecurityService.OutcomeDetails OutcomeDetails {
            get {
                return this.OutcomeDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeDetailsField, value) != true)) {
                    this.OutcomeDetailsField = value;
                    this.RaisePropertyChanged("OutcomeDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutcomeDetails", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.SecurityService.InvalidCredentials))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.SecurityService.PinNumberLockout))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.SecurityService.TaskAlreadyComplete))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HRServiceCalls.SecurityService.LoginLockout))]
    public partial class OutcomeDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HRServiceCalls.SecurityService.OperationOutcomeStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HRServiceCalls.SecurityService.OperationOutcomeStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectActions", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ObjectActions : HRServiceCalls.SecurityService.OperationOutcome {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, bool> ActionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, bool> Actions {
            get {
                return this.ActionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionsField, value) != true)) {
                    this.ActionsField = value;
                    this.RaisePropertyChanged("Actions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleItems", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class RoleItems : HRServiceCalls.SecurityService.OperationOutcome {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, bool> ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, bool> Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidCredentials", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class InvalidCredentials : HRServiceCalls.SecurityService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PinNumberLockout", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PinNumberLockout : HRServiceCalls.SecurityService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskAlreadyComplete", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class TaskAlreadyComplete : HRServiceCalls.SecurityService.OutcomeDetails {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginLockout", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    [System.SerializableAttribute()]
    public partial class LoginLockout : HRServiceCalls.SecurityService.OutcomeDetails {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationOutcomeStatus", Namespace="http://schemas.datacontract.org/2004/07/Cascade.HR.BLL.DataContracts")]
    public enum OperationOutcomeStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemException = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecurityService.ISecurityService")]
    public interface ISecurityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetRoleItemPermissions", ReplyAction="http://tempuri.org/ISecurityService/GetRoleItemPermissionsResponse")]
        HRServiceCalls.SecurityService.RoleItems GetRoleItemPermissions(System.Guid cascadeSessionToken, string[] roleItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetRoleItemPermissions", ReplyAction="http://tempuri.org/ISecurityService/GetRoleItemPermissionsResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.SecurityService.RoleItems> GetRoleItemPermissionsAsync(System.Guid cascadeSessionToken, string[] roleItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetObjectActionsForUser", ReplyAction="http://tempuri.org/ISecurityService/GetObjectActionsForUserResponse")]
        HRServiceCalls.SecurityService.ObjectActions GetObjectActionsForUser(System.Guid cascadeSessionToken, System.Guid employeeId, string objectType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/GetObjectActionsForUser", ReplyAction="http://tempuri.org/ISecurityService/GetObjectActionsForUserResponse")]
        System.Threading.Tasks.Task<HRServiceCalls.SecurityService.ObjectActions> GetObjectActionsForUserAsync(System.Guid cascadeSessionToken, System.Guid employeeId, string objectType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityServiceChannel : HRServiceCalls.SecurityService.ISecurityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityServiceClient : System.ServiceModel.ClientBase<HRServiceCalls.SecurityService.ISecurityService>, HRServiceCalls.SecurityService.ISecurityService {
        
        public SecurityServiceClient() {
        }
        
        public SecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HRServiceCalls.SecurityService.RoleItems GetRoleItemPermissions(System.Guid cascadeSessionToken, string[] roleItems) {
            return base.Channel.GetRoleItemPermissions(cascadeSessionToken, roleItems);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.SecurityService.RoleItems> GetRoleItemPermissionsAsync(System.Guid cascadeSessionToken, string[] roleItems) {
            return base.Channel.GetRoleItemPermissionsAsync(cascadeSessionToken, roleItems);
        }
        
        public HRServiceCalls.SecurityService.ObjectActions GetObjectActionsForUser(System.Guid cascadeSessionToken, System.Guid employeeId, string objectType) {
            return base.Channel.GetObjectActionsForUser(cascadeSessionToken, employeeId, objectType);
        }
        
        public System.Threading.Tasks.Task<HRServiceCalls.SecurityService.ObjectActions> GetObjectActionsForUserAsync(System.Guid cascadeSessionToken, System.Guid employeeId, string objectType) {
            return base.Channel.GetObjectActionsForUserAsync(cascadeSessionToken, employeeId, objectType);
        }
    }
}
